### ISSUE TITLE
Plugin crashes on latest Idea 14

### ISSUE THREAD

**Issue by riccardocossu** [jumperchen/zkidea#10]
When plugin starts it gives this error:

2015-10-10 18:33:04,694 [  13643]  ERROR - tartup.impl.StartupManagerImpl - java/util/Objects 
java.lang.NoClassDefFoundError: java/util/Objects
	at org.zkoss.zkidea.project.ZKProjectsManager.updateZulSchema(ZKProjectsManager.java:117)
	at org.zkoss.zkidea.project.ZKProjectsManager.access$100(ZKProjectsManager.java:45)
	at org.zkoss.zkidea.project.ZKProjectsManager$2.run(ZKProjectsManager.java:71)
	at com.intellij.util.DisposeAwareRunnable.run(DisposeAwareRunnable.java:82)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:339)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:331)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:191)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$8$2.run(ProjectManagerImpl.java:496)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: java.util.Objects PluginClassLoader[org.zkoss.zkidea, 0.1.6]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 25 more

**Comment by dorzhinov** [comment]
Class java.util.Objects has been introduced since java 7. Under which version of java you're running IDEA?
Also I know that the plugin has been compiled with java 8 compiler (according to http://forum.zkoss.org/question/98264/zkidea-unsupported-majorminor-version-520/), so you have to run IDEA under jvm 8.

**Comment by riccardocossu** [comment]
Thanks for your reply; it was running with Java 6.
It's a strange behavior from Idea, because, although I have installed Java 7 and 8, it uses that by default on Mac Os X.
Starting Idea with Java 8 solved the problem.

**Comment by riccardocossu** [comment]
I would suggest to add a warning for mac os users in the plugin page (you could link this bug).

**Comment by jumperchen** [comment]
It seems that Intellij plugin dependencies cannot run under JDK 6, even I fixed the Objects#equals issue that cannot solve this. Here is another workaround to run IntelliJ with JDK 7 only.
For example (in mac)
```
To force running under JDK 1.7 edit /Applications/<Product>.app/Contents/Info.plist file, change JVMVersion from 1.6* to 1.7* :

<key>JVMVersion</key>
<string>1.7*</string>
```

**Comment by riccardocossu** [comment]
that's one way to solve the problem but it's definitely not the best one; from the bug I linked:
1. Copied bin/idea.properties (from app's content) to ~/Library/Preferences/IntelliJIdea14/idea.properties file.
2. Changed JVMVersion=1.6* to JVMVersion=1.6+. (I have JDKs 1.6, 1.7 and 1.8 installed on my machine).
3. Launched IntelliJ IDEA Ultimate. It started with JDK 1.8.
