### ISSUE TITLE
Assertion on load of IDE/Project

### ISSUE THREAD

**Issue by bdaroz** [jumperchen/zkidea#17]
```
Assertion failed: Network shouldn't be accessed in EDT or inside read action
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
    at com.intellij.util.io.HttpRequests.process(HttpRequests.java:377)
    at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
    at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:251)
    at com.intellij.util.io.RequestBuilder.saveToFile(RequestBuilder.java:64)
    at org.zkoss.zkidea.project.ZKProjectsManager.updateZulSchema(ZKProjectsManager.java:141)
    at org.zkoss.zkidea.project.ZKProjectsManager.access$100(ZKProjectsManager.java:44)
    at org.zkoss.zkidea.project.ZKProjectsManager$2.run(ZKProjectsManager.java:70)
    at com.intellij.util.DisposeAwareRunnable.run(DisposeAwareRunnable.java:82)
    at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:342)
    at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:334)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:175)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:343)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:311)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:420)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:404)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:838)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by BorzdeG** [comment]
+1

IDEA IU-163.5219.11

**Comment by jumperchen** [comment]
Is this one? - [IntelliJ IDEA 2016.3 Early Access Program](https://www.jetbrains.com/idea/whatsnew/)
Because I cannot use its auto-update to get the 2016.3 version.

**Comment by bdaroz** [comment]
Yes I'm on:
```
IntelliJ IDEA 2016.3 EAP
Build #IU-163.5219.11, built on September 27, 2016
JRE: 1.8.0_112-release-b403 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

I've found the easiest way to manage the versions is to use the [Toolbox App](https://confluence.jetbrains.com/display/ToolboxApp/JetBrains+Toolbox+App+-+Early+Access+Program)

**Comment by BorzdeG** [comment]
I prefer the old ways
1) concrete pump build on the link "https://download.jetbrains.com/idea/idea%BUILD%.tar.gz" (to build "IU-163.5219.11" it will be a "https://download.jetbrains.com/idea/ideaIU-163.5219.11.tar.gz")
2) latest build page [EAP](https://confluence.jetbrains.com/display/IDEADEV/EAP)

**Comment by jumperchen** [comment]
Okay, I will build on top of that to see the issue.

**Comment by bdaroz** [comment]
Just a quick update - 2016.3 is now out of EAP and is the current production release. No change in the issue.
