### ISSUE TITLE
IDEA 2016.3: Network shouldn't be accessed in EDT or inside read action

### ISSUE THREAD

**Issue by connollyst** [jumperchen/zkidea#18]
I just upgraded to IntelliJ IDEA 2016.3
Build #IU-163.7743.44, built on November 18, 2016

JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

When first opening a ZK project I got the following error.

````
Assertion failed: Network shouldn't be accessed in EDT or inside read action
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:379)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:251)
	at com.intellij.util.io.RequestBuilder.saveToFile(RequestBuilder.java:64)
	at org.zkoss.zkidea.project.ZKProjectsManager.updateZulSchema(ZKProjectsManager.java:141)
	at org.zkoss.zkidea.project.ZKProjectsManager.access$100(ZKProjectsManager.java:44)
	at org.zkoss.zkidea.project.ZKProjectsManager$2.run(ZKProjectsManager.java:70)
	at com.intellij.util.DisposeAwareRunnable.run(DisposeAwareRunnable.java:82)
	at com.intellij.ide.startup.impl.StartupManagerImpl.d(StartupManagerImpl.java:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:336)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:175)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:343)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
````

**Comment by connollyst** [comment]
Duplicate of #17. Upgrading to the latest version of the plugin solves the problem.

Cheers!
