### ISSUE TITLE
Exception on Intellij IU-163.12024.16

### ISSUE THREAD

**Issue by macchid** [jumperchen/zkidea#19]
When initializing the ZK plugin for intellij, it reports the following exception:
```
java.lang.NegativeArraySizeException
	at org.zkoss.zkidea.project.ZKProjectsManager.download(ZKProjectsManager.java:159)
	at org.zkoss.zkidea.project.ZKProjectsManager.updateMavenArchetype(ZKProjectsManager.java:192)
	at org.zkoss.zkidea.project.ZKProjectsManager.access$200(ZKProjectsManager.java:45)
	at org.zkoss.zkidea.project.ZKProjectsManager$2.run(ZKProjectsManager.java:72)
	at com.intellij.util.DisposeAwareRunnable.run(DisposeAwareRunnable.java:82)
	at com.intellij.ide.startup.impl.StartupManagerImpl.d(StartupManagerImpl.java:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:336)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:175)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:343)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This happens even after reinstalling the plugin and with  a fresh install of Intellij Idea.
Got the same exception in Ubuntu 16.04 LTS 64 bits and on Mac OS Sierra.
Regards,

**Comment by jumperchen** [comment]
It looks like a unknown content length when downloading the latest schema, and it seems not to happen frequently, I already made a protection for this case, and will release it with other urgent issues, if any.

**Comment by tr1cks** [comment]
Can you make build with this fix or may be even release? I tried to do it, but it's not a maven project and looks like that you must know enough about idea plugins before get success. I think a lot of people will appreciate this.

**Comment by jumperchen** [comment]
Ok, it's released, please wait for the notification on Intellij.
